# Generated by Django 4.1.7 on 2023-03-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_filename', models.CharField(max_length=255)),
                ('original_detections', models.TextField()),
                ('detections', models.TextField()),
            ],
        ),
    ]
